package handlers

import (
	"context"
	"errors"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"

	"github.com/h44z/wg-portal/internal/config"
	"github.com/h44z/wg-portal/internal/domain"
)

type testSession struct {
	data SessionData
}

func (s *testSession) SetData(_ context.Context, val SessionData) {
	s.data = val
}

func (s *testSession) GetData(_ context.Context) SessionData {
	return s.data
}

func (s *testSession) DestroyData(_ context.Context) {
	s.data = SessionData{}
}

func newBasePathAuthEndpoint(session Session) AuthEndpoint {
	return AuthEndpoint{
		cfg: &config.Config{
			Web: config.WebConfig{
				ExternalUrl: "https://wg.example.com",
				BasePath:    "/subpath",
			},
		},
		session: session,
	}
}

// TestAuthEndpointIsValidReturnUrlRequiresBasePathApp pins the return URL shape that the frontend must
// produce. The accepted values are generated by externalLogin() in frontend/src/views/LoginView.vue
// from window.location - keep the two in sync when changing either side.
func TestAuthEndpointIsValidReturnUrlRequiresBasePathApp(t *testing.T) {
	ep := newBasePathAuthEndpoint(&testSession{})

	valid := []string{
		"https://wg.example.com/subpath/app/#/login",
		"https://wg.example.com/subpath/app/#/login?all=true",
		"https://wg.example.com/subpath/app/?beforeHash=true#/login",
	}
	for _, returnURL := range valid {
		if !ep.isValidReturnUrl(returnURL) {
			t.Fatalf("expected return URL to be valid: %s", returnURL)
		}
	}

	invalid := []string{
		"https://wg.example.com/#/login",
		"https://wg.example.com/subpath/#/login",
		"https://other.example.com/subpath/app/#/login",
	}
	for _, returnURL := range invalid {
		if ep.isValidReturnUrl(returnURL) {
			t.Fatalf("expected return URL to be invalid: %s", returnURL)
		}
	}
}

func TestAuthEndpointOauthCallbackRedirectsToBasePathHashRoute(t *testing.T) {
	session := &testSession{data: SessionData{
		LoggedIn:      true,
		OauthReturnTo: "https://wg.example.com/subpath/app/#/login",
	}}
	ep := newBasePathAuthEndpoint(session)

	req := httptest.NewRequest(http.MethodGet, "/api/v0/auth/login/google/callback", nil)
	req.SetPathValue("provider", "google")
	res := httptest.NewRecorder()

	ep.handleOauthCallbackGet().ServeHTTP(res, req)

	if res.Code != http.StatusFound {
		t.Fatalf("expected status %d, got %d", http.StatusFound, res.Code)
	}
	if got, want := res.Header().Get("Location"), "https://wg.example.com/subpath/app/#/login?wgLoginState=success"; got != want {
		t.Fatalf("expected redirect %q, got %q", want, got)
	}
}

func TestAuthEndpointReturnUrlWithLoginStatePreservesHashQuery(t *testing.T) {
	session := &testSession{data: SessionData{
		LoggedIn:      true,
		OauthReturnTo: "https://wg.example.com/subpath/app/#/login?all=true",
	}}
	ep := newBasePathAuthEndpoint(session)

	req := httptest.NewRequest(http.MethodGet, "/api/v0/auth/login/google/callback", nil)
	req.SetPathValue("provider", "google")
	res := httptest.NewRecorder()

	ep.handleOauthCallbackGet().ServeHTTP(res, req)

	if res.Code != http.StatusFound {
		t.Fatalf("expected status %d, got %d", http.StatusFound, res.Code)
	}
	if got, want := res.Header().Get("Location"), "https://wg.example.com/subpath/app/#/login?all=true&wgLoginState=success"; got != want {
		t.Fatalf("expected redirect %q, got %q", want, got)
	}
}

func TestAuthEndpointFrontendUrlUsesBasePathAppMount(t *testing.T) {
	ep := newBasePathAuthEndpoint(&testSession{})

	if got, want := ep.frontendUrl("/login"), "https://wg.example.com/subpath/app/#/login"; got != want {
		t.Fatalf("expected frontend URL %q, got %q", want, got)
	}
}

type dummyAuthService struct {
	loginErr error
	user     *domain.User
}

func (d dummyAuthService) GetExternalLoginProviders(_ context.Context) []domain.LoginProviderInfo {
	return nil
}
func (d dummyAuthService) PlainLogin(_ context.Context, username, password string) (*domain.User, error) {
	if d.loginErr != nil {
		return nil, d.loginErr
	}
	return d.user, nil
}
func (d dummyAuthService) OauthLoginStep1(_ context.Context, _ string) (string, string, string, string, error) {
	return "", "", "", "", nil
}
func (d dummyAuthService) OauthLoginStep2(_ context.Context, _, _, _, _ string) (*domain.User, string, error) {
	return nil, "", nil
}
func (d dummyAuthService) OauthProviderLogoutUrl(_, _, _ string) (string, bool) {
	return "", false
}

type dummyValidator struct{}

func (d dummyValidator) Struct(_ any) error {
	return nil
}

func TestAuthEndpointHandleLoginPostRejectsInvalidCredentialsEvenIfSessionDirty(t *testing.T) {
	session := &testSession{data: SessionData{
		LoggedIn:       true,
		UserIdentifier: "previous-user",
	}}
	ep := AuthEndpoint{
		session:     session,
		authService: dummyAuthService{loginErr: errors.New("auth failed")},
		validate:    dummyValidator{},
	}

	req := httptest.NewRequest(http.MethodPost, "/api/v0/auth/login", strings.NewReader(`{"username":"admin","password":"wrongpassword"}`))
	req.Header.Set("Content-Type", "application/json")
	res := httptest.NewRecorder()

	ep.handleLoginPost().ServeHTTP(res, req)

	if res.Code != http.StatusUnauthorized {
		t.Fatalf("expected status %d (Unauthorized), got %d", http.StatusUnauthorized, res.Code)
	}
}
