apiVersion: v1
kind: Service
metadata:
  {{- with .Values.service.web.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
  name: {{ include "wg-portal.fullname" . }}-web
  labels: {{- include "wg-portal.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector: {{- include "wg-portal.selectorLabels" . | nindent 4 }}
  type: {{ .Values.service.web.type }}
