{
 "title": "WireGuard Portal",
 "description": "WireGuard Portal Dashboard",
 "tags": [
  "wireguard",
  "vpn"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(wireguard_interface_sent_bytes_total,instance)"
    }
   },
   {
    "name": "interface",
    "label": "Interface",
    "query": {
     "query": "label_values(wireguard_interface_sent_bytes_total{instance=\"$instance\"},interface)"
    }
   },
   { "name": "interval", "label": "Step Interval", "query": "30s,1m,2m,5m,10m" }
  ]
 },
 "panels": [
  {
   "title": "Interface Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, interface) (wireguard_interface_received_bytes_total{instance=\"$instance\", interface=~\"$interface\"})",
     "legendFormat": "Received {{interface}}"
    },
    {
     "expr": "sum by (instance, interface) (wireguard_interface_sent_bytes_total{instance=\"$instance\", interface=~\"$interface\"})",
     "legendFormat": "Sent {{interface}}"
    }
   ]
  },
  {
   "title": "Interface Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, interface) (rate(wireguard_interface_received_bytes_total{instance=\"$instance\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "Received {{interface}}"
    },
    {
     "expr": "sum by (instance, interface) (rate(wireguard_interface_sent_bytes_total{instance=\"$instance\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "Sent {{interface}}"
    }
   ]
  },
  {
   "title": "Peer Receive Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name, instance, interface) (rate(wireguard_peer_received_bytes_total{instance=\"$instance\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Peer Transmit Bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, interface, name) (rate(wireguard_peer_sent_bytes_total{instance=\"$instance\", interface=~\"$interface\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Peer Connection History",
   "type": "status-history",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sum by(name) (wireguard_peer_up{instance=\"$instance\", interface=~\"$interface\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Peer Info",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sum by(id, instance, interface, name, addresses) (increase(wireguard_peer_received_bytes_total{instance=\"$instance\", interface=~\"$interface\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(id, instance, interface, name) (increase(wireguard_peer_sent_bytes_total{instance=\"$instance\", interface=~\"$interface\"}[$__range]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "time()-sum(wireguard_peer_last_handshake_seconds{instance=\"$instance\", interface=~\"$interface\"}) by(id, instance, interface, name) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(wireguard_peer_up{instance=\"$instance\", interface=~\"$interface\"}) by(id, instance, interface, name) ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}